# Generated by Django 2.0.4 on 2018-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0002_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='established',
            field=models.DateField(auto_now_add=True),
        ),
    ]
