# Generated by Django 2.0.4 on 2018-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0009_auto_20180508_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
