# Generated by Django 2.0.4 on 2018-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POSsystem', '0011_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
